apiVersion: v1
kind: DaemonSet
metadata:
  name:  my-daemonset
spec:
  selector:
    matchlabels:
      app: my-daemonset
  template:
    metadata:
      labels:
        app: my-daemonset
    spec:
      containers:
        - image:  nginx:1.19.1
          name:  nginx