apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','while true; do sleep 3600;done']
    livenessProbe:
      exec:
        command: ["echo","Hello, Liveness Probe: Pod is OK"]
      initialDelaySeconds: 5
      periodSeconds: 5