apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod-http
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5