apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5