apiVersion: v1
kind: Pod
metadata:
  name: startup-pod
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
    startupProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 30
      periodSeconds: 15