apiVersion: v1
kind: Pod
metadata:
  name: sidecar-init-container
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c','while true; do cat /opt/logs.txt; sleep 3600; done']
    volumeMounts:
    - name: sharedvolume
      mountPath: /opt
  initContainers:
  - name: initsidecar
    image: busybox
    restartPolicy: Always
    command: ['sh','-c','echo "k8s is super cool. i am a GURU now" >> /opt/logs.txt']
    volumeMounts:
    - name: sharedvolume
      mountPath: /opt
  volumes:
  - name: sharedvolume
    emptyDir: {}