apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ['sh','-c','while true; do echo logs data > /output/output.log; sleep 5; done']
    volumeMounts:
    - name:  sharevol
      mountPath:  /output
  - image: busybox
    name: sidecar
    command: ['sh','-c','tail -f /input/output.log']
    volumeMounts:
    - name:  sharevol
      mountPath:  /input
  volumes:
  - name:  sharevol
    emptyDir:  {}