apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - image: nginx:1.19.1
    name: nginx
  initContainers:
  - name: delay
    image:  busybox
    command:
      - sleep
      - "30"