apiVersion: v1
kind: Pod
metadata:
  name: big-requests-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','while true; do sleep 3600;done']
    resources:
      requests:
        cpu: "100000m"
        memory: "128Mi"