apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: lifetime-pod
  name: lifetime-pod
spec:
  serviceAccountName: sa-lifetime
  containers:
  - image: bitnami/kubectl
    name: lifetime-pod
    command: ['sh','-c','sleep 4800']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}